# Generated by Django 4.2.6 on 2023-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_age_customuser_bio_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], default='USER', max_length=4),
        ),
    ]
