# Generated by Django 4.2.6 on 2023-11-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(limit_choices_to={'user_type': 'FAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='fan_conversations', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(limit_choices_to={'user_type': 'MODEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fan', 'model')},
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
    ]
